# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('film_rating', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
