# Generated by Django 2.0 on 2018-01-23 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessapplication',
            name='appToken',
            field=models.CharField(default=datetime.datetime(2018, 1, 23, 14, 44, 47, 165078, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessapplication',
            name='appSecret',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
